#spring.application.name=pagamento-service

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/pedidos
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
