#spring.application.name=pagamento-service

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: pagamento-group
      auto-offset-reset: earliest

server:
  port: 8081