#spring.application.name=pedido-service

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/pedidos_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      novo-pedido: novo-pedido-topic
      pagamento-processado: pagamento-processado-topic

server:
  port: 8082
