#spring.application.name=pedido-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pedidos_db
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092
  topic:
    novo-pedido: novo-pedido-topic
    pagamento-processado: pagamento-processado-topic

server:
  port: 8082
